---
  - name: Create partition
    parted:
      device: "{{ device }}"
      number: 1
      state: present
      part_end: "{{ partition_size }}"

  - name: Format partition
    filesystem:
      fstype: xfs
      dev: "{{ device }}1"

  - name: Set new UUID for XFS file system 
    raw: xfs_admin -U "{{ uuid }}" /dev/sdb1

  - name: Mount the partition by UUID in fstab
    mount:
      src: "UUID={{ uuid }}"
      path: "{{ mount_point }}"
      state: mounted
      fstype: xfs
      opts: defaults

  - name: Add Filesystem to fstab
    lineinfile:
      path: /etc/fstab
      line: "UUID={{ uuid }} {{ mount_point }} xfs defaults 0 0"
      state: present
 

